# Read the testing-graphql.md file to learn how to run the queries or add new tests

@baseURL = {{$dotenv WP_BASE_URL}}

# Note: This query will only work if:
# 1. There are published pages in WordPress
# 2. The pages are publicly queryable

### Get All Pages
POST {{baseURL}}/graphql
Content-Type: application/json

{
    "query": "query GetPages { pages { nodes { id title content } } }"
}